In [1]:
import numpy as np

# Creating arrays

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10, 2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
python_list = [1, 2, 5, 7]
a = np.array(python_list)

In [12]:
a[0]

np.int64(1)

In [13]:
a[2]

np.int64(5)

In [14]:
a

array([1, 2, 5, 7])

In [ ]:
# assigment to change the value

In [16]:
a[2] = 10

In [17]:
a

array([ 1,  2, 10,  7])

In [20]:
np.arange(10) # exclusive 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(3, 10) # exclusive 10

array([3, 4, 5, 6, 7, 8, 9])

In [23]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multi-dimensional arrays

In [27]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
np.zeros(((5, 2)))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
n = np.array([
    [1, 2, 5], # 0 row
    [4, 6, 7] # 1 row
])

In [33]:
n[0, 1] # first row, after column

np.int64(2)

In [34]:
n[0, 1] = 20

In [35]:
n

array([[ 1, 20,  5],
       [ 4,  6,  7]])

In [37]:
n[:, 0]

array([1, 4])

# Randomly generated arrays

In [41]:
np.random.rand(5, 2)

array([[0.13719897, 0.3978519 ],
       [0.28637295, 0.89141735],
       [0.03641233, 0.2207196 ],
       [0.04337913, 0.64639286],
       [0.66396132, 0.57333763]])

In [44]:
np.random.seed(10)
np.random.rand(5, 2) # random numbers will always be the same

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [45]:
np.random.seed(10)
np.random.randn(5, 2) # normal distribution

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021]])

In [46]:
np.random.seed(10)
100 * np.random.randn(5, 2) # normal distribution

array([[ 133.15865041,   71.52789744],
       [-154.54002921,   -0.83838499],
       [  62.13359739,  -72.00855607],
       [  26.55115857,   10.85485257],
       [   0.42914309,  -17.46002106]])

In [47]:
np.random.seed(10)
100 * np.random.randint(low=0, high=100, size=(5, 2)) # normal distribution

array([[ 900, 1500],
       [6400, 2800],
       [8900, 9300],
       [2900,  800],
       [7300,    0]])

# Element-wise operations

In [48]:
a = np.arange(5)

In [50]:
a + 1 # python is not possible, needs to interate

array([1, 2, 3, 4, 5])

In [51]:
a * 2

array([0, 2, 4, 6, 8])

In [54]:
b = ( 10 + (a *2) **2 )/100

In [55]:
a + b

array([0.1 , 1.14, 2.26, 3.46, 4.74])

# Comparison operations

In [58]:
a >= 2

array([False, False,  True,  True,  True])

In [61]:
a > b

array([False,  True,  True,  True,  True])

In [62]:
a[a > b]

array([1, 2, 3, 4])

In [63]:
a[a > 2]

array([3, 4])

# Summarizing operations

In [64]:
a.min()

np.int64(0)

In [65]:
a.max()

np.int64(4)

In [66]:
a.sum()

np.int64(10)

In [67]:
a.mean()

np.float64(2.0)

In [68]:
a.std()

np.float64(1.4142135623730951)

In [69]:
n

array([[ 1, 20,  5],
       [ 4,  6,  7]])

In [70]:
n.sum()

np.int64(43)

In [71]:
n.std()

np.float64(6.039223643997812)

In [74]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

In [75]:
u * v 

array([ 2,  0,  0, 12])

In [77]:
# in algebra, the result would be:

(u * v).sum()

np.int64(14)

In [ ]:
d

In [83]:
def vector_vector_multiplication(u, v):

    assert u.shape[0] == v.shape[0]

    result = 0
    for i in range(u.shape[0]):
        result += u[i] * v[i]

    return result

In [84]:
a = vector_vector_multiplication(u, v)

In [85]:
a

np.int64(14)

In [86]:
u.dot(v)

np.int64(14)

In [87]:
def matrix_vector_multiplication(U, v):

    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result[i]

In [99]:
U = np.random.rand(4, 2)

In [100]:
U

array([[0.06556327, 0.05644419],
       [0.76545582, 0.01178803],
       [0.61194334, 0.33188226],
       [0.55964837, 0.33549965]])

In [101]:
v

array([1, 0, 0, 2])

In [103]:
matrix_vector_multiplication(U, v)

AssertionError: 

In [107]:
I = np.eye(4)

In [108]:
U.dot(I)

ValueError: shapes (4,2) and (4,4) not aligned: 2 (dim 1) != 4 (dim 0)